# Generated by Django 3.2.16 on 2023-11-10 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community_name', models.CharField(max_length=50, verbose_name='community_name')),
            ],
            options={
                'verbose_name': 'Comunidad',
                'verbose_name_plural': 'Comunidades',
                'db_table': 'Community',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_title', models.CharField(max_length=100, verbose_name='rule_title')),
                ('rule_content', models.TextField(verbose_name='rule_content')),
            ],
            options={
                'verbose_name': 'Regla',
                'verbose_name_plural': 'Reglas',
                'db_table': 'Rule',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50, unique=True, verbose_name='user_name')),
                ('user_image', models.ImageField(blank=True, null=True, upload_to='posts/%Y/%m/%d', verbose_name='user_image')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'User',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.TextField(max_length=100, verbose_name='post_title')),
                ('post_content', models.TextField(verbose_name='post_content')),
                ('post_date', models.DateTimeField(verbose_name='post_date')),
                ('post_votes', models.IntegerField(default=0, verbose_name='post_votes')),
                ('post_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='redditClone.user', verbose_name='post_author')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'db_table': 'Post',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Commentary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentary_content', models.TextField()),
                ('commentary_date', models.DateTimeField()),
                ('commentary_response_id', models.PositiveBigIntegerField(null=True)),
                ('commentary_votes', models.IntegerField(default=0, verbose_name='post_votes')),
                ('commentary_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='redditClone.user', verbose_name='post_author')),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
                'db_table': 'Commentary',
                'ordering': ['id'],
            },
        ),
    ]
