# Generated by Django 3.2.16 on 2023-11-10 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('redditClone', '0002_rule_rule_community'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentary',
            name='commentary_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='redditClone.user', verbose_name='commentary_author'),
        ),
        migrations.AlterField(
            model_name='commentary',
            name='commentary_votes',
            field=models.IntegerField(default=0, verbose_name='commentary_votes'),
        ),
    ]
